Qpaper/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('home/',views.index,name = 'index'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register',views.signup_user,name = 'signup_user'),
    path('login',views.signin_user,name = 'signin_user'),
    path('logout',views.logout_user,name = 'logout_user'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.home,name = 'home'),
    path('upload-file',views.upload,name = 'upload'),
    path('search',views.search,name = 'search'),
    path('detail/post_id:<int:pk>/',views.detail,name = 'detail'),
    path('detail/edit/<int:pk>/',views.update,name = 'update'),
    path('detail/delete/<int:pk>/', views.delete, name='delete'),
    path('postanswer/<int:pk>/',views.postanswer,name = 'postanswer'),
    path('update-answer/<int:pk>/ans/<int:ans_id>/',views.update_ans,name = 'update_ans'),
    path('delete_ans/<int:pk>/ans/<int:ans_id>/',views.delete_ans, name = 'delete_ans'),
    path('about-page',views.aboutpage,name = 'aboutpage'),
    path('contact-page',views.contactme,name = 'contactme'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Year(models.Model):
    year = models.CharField(max_length = 10)
    value = models.CharField(max_length = 10)

    def __str__(self):
        return self.year

class Question(models.Model):
    trade = models.CharField(max_length = 10)
    semester = models.CharField(max_length = 10)
    subject = models.CharField(max_length = 20)
    exam = models.CharField(max_length = 10)
    year_of_exm = models.CharField(max_length = 10)
    file = CloudinaryField(resource_type ='image',folder = 'questions_Qpaper')
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    date_published = models.DateTimeField()
    def __str__(self):
        return self.trade +"|"+self.semester+"|"+self.exam+"|"+self.year_of_exm+'|' + self.subject + "|" + "by " + self.owner.username

class Answer(models.Model):
    post = models.ForeignKey(Question, on_delete = models.CASCADE,related_name = 'answers')
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    context = models.CharField(max_length = 30,blank = False)
    image = CloudinaryField(resource_type ='image',folder = 'answers_Qpaper')
    date_published = models.DateTimeField()

    def __str__(self):
        return f"{self.post.trade}|{self.post.semester}Sem|{self.post.subject}|{self.post.year_of_exm}|{self.post.exam} by {self.owner}"

home/forms.py
from django.forms import ModelForm
from .models import Question

class UpdateForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

home/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .models import Question,Year,Answer
from .choices import trade_choices,sem_choices,exm_choices,subject_choices
from django.contrib import  messages
from .forms import UpdateForm
import datetime


from django.http import Http404
def home(r):
   if r.method == 'GET':
       fiels = Question.objects.all().order_by('-date_published')
       yr = Year.objects.all()

       return render(r,'index.html',{'fiels':fiels,'yr':yr,'sems':sem_choices,'trades':trade_choices,'exm':exm_choices,'subject':subject_choices})




def index(r):
    return redirect('home:home')


def upload(r):

    if r.method == 'GET':
        if r.user.is_authenticated:
            yr = Year.objects.all()
            return render(r,'upload.html',{'sems':sem_choices,'trades':trade_choices,'exm':exm_choices,'yr':yr,'subject':subject_choices})
        else:
            return render(r,'error.html')
    else:
        try:
            trade = r.POST.get('trade')
            sem = r.POST.get('sem')
            exm = r.POST.get('exm')
            up_file = r.FILES['up']
            up_year = r.POST.get('year_sec')
            up_subject = r.POST.get('sub_sec')
            x = datetime.datetime.now()

            col = Question(trade=trade,semester=sem,file=up_file,exam = exm,year_of_exm = up_year,subject = up_subject,owner = r.user,date_published = x)
            col.save()
            print("Your file has been uploaded successfully")
            messages.success(r, 'Your file has been uploaded successfully')
            return redirect('home:home')
        except Exception as e:

            print("Error in uploading")
            print(e)
            print(r)
            messages.error(r, 'Could not upload, try again')
            return redirect('home:upload')



def search(r):

    if r.method == "GET":

        values = r.GET

        try:
            if 'trade_sec' in r.GET and 'sem_sec' in r.GET and 'exm' in r.GET and 'year_sec' in r.GET and 'sub_sec' in r.GET:
                     trade = r.GET['trade_sec']
                     yr = r.GET['year_sec']
                     exm_c = r.GET['exm']
                     sem = r.GET['sem_sec']
                     sub = r.GET['sub_sec']
                     collection = Question.objects.filter(semester__iexact=sem,trade__iexact =trade,year_of_exm__iexact = yr,exam__iexact = exm_c,subject__iexact = sub).order_by('-date_published')
            elif 'trade_sec' in r.GET and 'sem_sec' in r.GET and 'exm' in r.GET and 'year_sec' in r.GET: 
                     trade = r.GET['trade_sec']
                     yr = r.GET['year_sec']
                     exm = r.GET['exm']
                     sem = r.GET['sem_sec']
                   
                     collection = Question.objects.filter(semester__iexact=sem,trade__iexact =trade,year_of_exm__iexact = yr,exam__iexact = exm,).order_by('-date_published')
            
            
            
            elif 'trade_sec' in r.GET and 'sem_sec' in r.GET and 'year_sec' in r.GET and 'sub_sec' in r.GET:
                     trade = r.GET['trade_sec']
                     yr = r.GET['year_sec']
                     sem = r.GET['sem_sec']
                     sub = r.GET['sub_sec']
                     collection = Question.objects.filter(semester__iexact=sem,trade__iexact =trade,year_of_exm__iexact = yr,subject__iexact = sub).order_by('-date_published')


            elif 'trade_sec' in r.GET and 'exm' in r.GET and 'sem_sec' in r.GET and 'sub_sec' in r.GET:
                     trade = r.GET['trade_sec']
                     exm = r.GET['exm']
                     sem = r.GET['sem_sec']
                     sub = r.GET['sub_sec']
                     collection = Question.objects.filter(exam__iexact=exm,trade__iexact =trade,semester=sem,subject__iexact = sub).order_by('-date_published')
            elif 'trade_sec' in r.GET and 'sub_sec' in r.GET and 'sem_sec' in r.GET:
                     trade = r.GET['trade_sec']
                     sub = r.GET['sub_sec']
                     sem = r.GET['sem_sec']
                     collection = Question.objects.filter(subject__iexact=sub,trade__iexact =trade,semester=sem).order_by('-date_published')

            elif 'trade_sec' in r.GET and 'exm' in r.GET and 'sem_sec' in r.GET:
                     trade = r.GET['trade_sec']
                     exm = r.GET['exm']
                     sem = r.GET['sem_sec']
                     collection = Question.objects.filter(exam__iexact=exm,trade__iexact =trade,semester=sem).order_by('-date_published')
            elif 'trade_sec' in r.GET and 'sub_sec' in r.GET:
                     trade = r.GET['trade_sec']
                     sub = r.GET['sub_sec']
                     collection = Question.objects.filter(trade__iexact=trade,subject__iexact = sub).order_by('-date_published')

            elif 'trade_sec' in r.GET and 'sem_sec' in r.GET :
                     trade = r.GET['trade_sec']
                     sem = r.GET['sem_sec']
                     collection = Question.objects.filter(semester__iexact=sem,trade__iexact =trade).order_by('-date_published')
            elif 'trade_sec' in r.GET and 'exm' in r.GET :
                     trade = r.GET['trade_sec']
                     exm = r.GET['exm']
                     collection = Question.objects.filter(exam__iexact=exm,trade__iexact =trade).order_by('-date_published')
            elif 'trade_sec' in r.GET and 'year_sec' in r.GET :
                     trade = r.GET['trade_sec']
                     yr = r.GET['year_sec']
                     collection = Question.objects.filter(year_of_exm__iexact = yr,trade__iexact =trade).order_by('-date_published')
            elif 'sem_sec' in r.GET and 'sub_sec' in r.GET and 'year_sec' in r.GET:
                sem = r.GET['sem_sec']
                sub = r.GET['sub_sec']
                yr = r.GET['year_sec']
                collection = Question.objects.filter(subject__iexact=sub, semester__iexact=sem,year_of_exm__iexact = yr).order_by('-date_published')
            elif 'sem_sec' in r.GET and 'exm' in r.GET and 'year_sec' in r.GET:
                sem = r.GET['sem_sec']
                exm = r.GET['exm']
                yr = r.GET['year_sec']
                collection = Question.objects.filter(exam__iexact=exm, semester__iexact=sem,year_of_exm__iexact = yr).order_by('-date_published')

            elif 'sem_sec' in r.GET and 'year_sec' in r.GET:
                sem = r.GET['sem_sec']
                yr = r.GET['year_sec']
                collection = Question.objects.filter(semester__iexact=sem,year_of_exm__iexact=yr).order_by('-date_published')

            elif 'sem_sec' in r.GET and 'sub_sec' in r.GET:
                sem = r.GET['sem_sec']
                sub = r.GET['sub_sec']
                collection = Question.objects.filter(subject__iexact=sub,semester__iexact=sem).order_by('-date_published')
            elif 'sem_sec' in r.GET:
                sem = r.GET['sem_sec']
                collection = Question.objects.filter(semester__iexact=sem).order_by('-date_published')
            elif 'trade_sec' in r.GET:
                trade = r.GET['trade_sec']
                collection = Question.objects.filter(trade__iexact=trade).order_by('-date_published')
            elif 'sub_sec' in r.GET:
                sub = r.GET['sub_sec']
                collection = Question.objects.filter(subject__iexact=sub).order_by('-date_published')
            elif 'exm' in r.GET:
                exam_choose = r.GET['exm']
                collection = Question.objects.filter(exam__iexact=exam_choose).order_by('-date_published')


            else:
                messages.error(r,'Select all the fields!!!')
                return redirect('home:home')

        except:
            print("=================================")
        all_year = Year.objects.all()


        return render(r,'result.html',{'fiels':collection,'values':values,'sems':sem_choices,'trades':trade_choices,'exm':exm_choices,'all_year':all_year,'subject':subject_choices})
    else:


        return redirect('home:home')


def detail(r,pk):
    detail = get_object_or_404(Question,id = pk)
    answers = Answer.objects.filter(post = detail).order_by('-date_published')
    return  render(r,'details.html',{'detail':detail,'answers':answers})

def update(r,pk):

    yr = Year.objects.all() 
    to_update = Question.objects.get(id = pk) #get_object_or_404(Question,id = pk)
    if r.method == "GET":
        if   to_update.owner.id != r.user.id:
             # raise Http404
             print("You are not the user")
             return render(r, 'error.html')
        else:
          return render(r,'update.html',{'to_update':to_update,'sems':sem_choices,'trades':trade_choices,'exm':exm_choices,'yr':yr,'subject':subject_choices})
    else:
        if to_update.owner != r.user:
             # raise Http404
             return render(r, 'error.html')
        else:
            try:
                trade = r.POST.get('trade')
                sem = r.POST.get('sem')
                exm = r.POST.get('exm')
                up_file = r.FILES['up']
                up_year = r.POST.get('year_sec')
                up_subject = r.POST.get('sub_sec')
                owner = to_update.owner
                x =datetime.datetime.now()
                col = Question(id = pk,trade=trade,semester=sem,file=up_file,exam = exm,year_of_exm = up_year,subject = up_subject,owner = owner, date_published = x)
                col.save()
                messages.success(r, 'Successfully Updated')
                return redirect('home:home',to_update.id)
            except Exception as e:

                print('Error in updating')
                print(e)
                messages.error(r, 'Could not update, Try again')
                return redirect('home:detail',to_update.id)


def delete(r,pk):
    if r.method == "POST":
        to_delete = get_object_or_404(Question, pk=pk)

home/templates/about.html
{% extends 'base.html' %}
{% block title %}
About us
{% endblock %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
<section id="about">
    <div class="about-hero">
        <h3>You are looking at the about page of this web application</h3>
        <div class="about-info">
            <br>
          <p>This website was created by  <a href="{% url 'home:contactme' %}">me</a> to solve the  difficulties in searching of previous questions and answers </p>
          <p>This website is mainly for the students of Manipur Institute and technology,Imphal</p>
          <p>There is nothing special in this website but </p>
		  <p> This will help us in some of the difficulties we faced in searching of QnA of the previous exam</p>
          <br>
          <p>You can upload in image(png/jpeg) or pdf file format only</p>
          <br>
          <p>Please do not upload any big size file in case you want to upload please lower down the quality 
            
        </p>
		<p>Anything unrelated with the scope of this website will be delete</p>
        <p> Please support my Qpaper webiste for MIT</p>


        </div>
        <div class="instruction">
            <h1>Instruction</h1>
            <ul>
                <li>Register and Login </li>
                <li>Upload the question papers</li>
                <li>Go to the uploaded Question paper and add ans image/pdf to those Qs</li>
                <li>You can delete or update QnA images/pdf file </li>
                <li>Bookmark this webiste so that it will be easy to find when you need Qpaper</li>
				<li>Leave feedback in the contact section</li>
            </ul>
        </div>
    </div>


</section>
{% endblock %}

home/templates/ansupdate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Q{{post.id}}-Ans-{{ans.id}}-edit{% endblock %}
{% block style%}
<link rel="stylesheet" href="{% static 'css/update-post.css' %}">
{% endblock %}

{% block content %}

<section id="answers">
<div class="update-container">
    <h2>Update Answer details here</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'home:update_ans' post.id ans.id %}">
        {% csrf_token %}
    <div class="row-update">
        <div class="col">
            <label for="">Description:</label>
            <input class="des" type="text" name="context" required value="{{ans.context}}">
        </div>
        <div class="col">
            <h3>Currently file = <a href="{{ans.image.url}}">URL</a></h3>
            <p>You are required to choose the file (jpeg/png/pdf) to upload</p>
            <br>
            <input type="file" name="ans-file" required value="{{ans.image.url}}">
        </div>
        <div class="col btn-container">
            <button class="btn" type="submit" name="upload">Upload</button>
        </div>
    </div>
</div>

</section>


{% endblock %}

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width,initial-scale=1.0"> -->
    <meta name="description" content = "This website allows students of Manipur Institute of Technology to share previous years Questions and Answers online">
    <meta name="keywords" content="Manipur Institute of Technology, Previous year Questions and Answers,Question paper,Answers,College,Students">
    <meta name="author" content="James Haobam">
    {% block meta %}

    {% endblock %}
    <title>Qpaper-{% block title %}{% endblock %}</title>
   <link rel="shortcut icon" href="{% static 'images/favlogo.png'%}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block style%}
    {% endblock %}
</head>
<body>
  <div class="preload">
    <div class="loading">
  
    </div>
  </div>
  
<!-- -------------------------header---------------------------- -->
<header>
  <div class="header-container">
    <div class="logo-container">
      <a href="{% url 'home:home' %}"><img src="{% static 'images/logo.png' %}" alt="logo for qpaper mit "></a>
     
    </div>
    <nav class="navbar">
      <ul class="items">
        <li class="item"><a href="{% url 'home:home' %}">Home</a></li>
        {% if user.is_authenticated %}
        <li class="item"><a href="{% url 'home:upload' %}">Upload</a></li>
        <form class="lg-form" method="post" action="{% url 'account:logout_user' %}">
          {% csrf_token %}
          <input class="item log-lg" type="submit" value="Logout">
      </form>
        

        {% else %}
        <li class="item"><a href="{% url 'account:signin_user' %}">Login</a></li>
        <li class="item"><a href="{% url 'account:signup_user' %}">Register</a></li>
        {% endif %}
        
        
        
        <li class="item"><a href="{% url 'home:aboutpage' %}">About</a></li>
        <li class="item"><a href="{% url 'home:contactme' %}">Contact</a></li>
      </ul>
    </nav>

    <!-- ---------------Only activate when humberger menu is clicked-------------------------------- -->
    
    <nav class="nav-small">
      <ul class="links">
        <li class="link"><a href="{% url 'home:home' %}">Home</a></li>
        {% if user.is_authenticated %}
        <li class="link"><a href="{% url 'home:upload' %}">Upload</a></li>
        <form method="post" action="{% url 'account:logout_user' %}">
          {% csrf_token %}
          <input class="link logout" type="submit" value="Logout">
      </form>
        

        {% else %}
        <li class="link login"><a href="{% url 'account:signin_user' %}">Login</a></li>
        <li class="link register"><a href="{% url 'account:signup_user' %}">Register</a></li>
        {% endif %}
        
        
        
        <li class="link"><a href="{% url 'home:aboutpage' %}">About</a></li>
        <li class="link"><a href="{% url 'home:contactme' %}">Contact</a></li>
      </ul>
    </nav>

    <div class="menu">
      <img class="menu-logo" src="{% static 'images/greenmenu.png' %}" alt="menu-icon">
    </div>
  <!-- ---------------------XXXXXX--------------------------- -->

  </div>

</header>
  
<section class="welcome">
    
  {% if user.is_authenticated %}
  <h3>Welcome!<span> {{user.username}}</span></h3>
    {% if user.first_name and  user.last_name %}
    <p>Full name: {{user.first_name}} {{user.last_name}}</p>
    {% else %}
    <p>Full name: No full name registered</p> 
    {% endif %}
  <!-- <p>User id: {{user.id}}</p> -->

  {% else %}
  <h1>Login to share Questions and Answers</h1>
  {% endif %}
 

</section>

   <hr>
   {% block search %}
   
   {% endblock %}
   {% block content %}
   
   {% endblock %}
</div>
   






<section id="footer">
<footer>
  <p>Copyright &copy 2020-2021</p> 
</footer>
</section>
{% block script %}
<script src="{% static 'js/app.js' %}"></script>
{% endblock %}
<script>
  const overlay = document.querySelector('.preload');
  window.addEventListener('load', () => {
    overlay.style.display = 'none';
  });

</script>

</body>
</html>

home/templates/contactme.html
{% extends 'base.html' %}
{% block title %}
Contact the developer
{% endblock %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block content %}
<section id="contact-me">
    <div class="contact-hero">
        <div class="hero">
            <h1>Below is my contact details</h1>
        </div>

          <div class="contact-info">
                      
        <p>In case you have querie about the website or you want to contact me</p>
        <br>
              <a href="mailto:helpqpaper@gmail.com?subject = Feedback&body = Message">helpqpaper@gmail.com</a>
              <br>
              <p>Don't forget to Send feed back as well</p>
          </div>

    </div>
    



</section>
{% endblock %}

home/templates/details.html
{% extends 'base.html' %}
{% block meta %}
<meta name="description" content="Details of {{detail.id}} and answers {{answers}}">
<meta name="keywords" name="MIT previous year Questions and Answers">
{% endblock %}
{% load static %}
{% block title %}Info-{{detail.id}}{% endblock %}
{% block style%}
<link rel="stylesheet" href="{% static 'css/details.css' %}">
{% endblock %}
{% block search %}
<!-- <a href="{% url 'home:home' %}">Back to home</a> -->
{% endblock %}
{% block content %}
<main>
    <div class="messages">
        <!-- <h3>Message here</h3> -->
        <div class="mssg">
          {% if messages %}
          <script>
            const msg = document.querySelector('.messages');
             msg.style.display = 'flex'
          </script>
           {% for messages in messages %}
               <p>{{messages}}</p>
           {% endfor %} 
        {% endif %}
        <div class="close">
            <h5>&#10062</h5>
          </div>
          </div>
          </div>

<section id="img-container">
    <div class="img-hero">

        <img style = "font-size: 2rem;color:red;" src="{{detail.file.url}}" alt="You see this because this file is pdf" width="100%" height="100%">
    </div>


</section>

<section id="information">
    <div class="info-hero">
        Trade: {{detail.trade}}
        <br>
        Year: {{detail.year_of_exm}}
        <br>
        Examination: {{detail.exam}}
        <br>
        Semester: {{detail.semester}}
        <br>
         <p>Subject: {{detail.subject}} </p>
        <p>Shared by: {{detail.owner.username}} {% if request.user.id == detail.owner.id  %}(You){% else %} {% endif %}</p>
        <p>on <small> {{detail.date_published}}</small></p>
        <div class="link-container">
            <a class="download" href="{{detail.file.url}}" target="_blank">Download the file</a>
       
            {% if request.user.id == detail.owner.id  %}
<a class="edit" href="{% url 'home:update' detail.id %}">Edit</a>
<form id="form" action="{% url 'home:delete' detail.id %}">
    {% csrf_token %}
    <button type="submit" class="delete" id="del-btn">delete</button>

    <script>
    const btn = document.querySelector("#del-btn");
     btn.addEventListener("click",() => {
    let ask_true = confirm("Are you sure?")
    if(ask_true == true){
      document.querySelector("#form").setAttribute("method","POST");
    }
    else{
        document.querySelector("#form").setAttribute("method","GET");
    }


     });

</script>

</form>

{% else %}
{% endif %}
        </div>
        
    </div>
    
</section>


<hr>
<br>

<!-- --------------------- Answer section --------------------- -->

<section id="answers">
    <div class="ans-hero">
        <div class="ans-title">
            <h1>Answers to these Questions</h1>
        </div>
        <div class="ans-add">
            <strong>Add answers for the above questions:</strong>
            <form action="{% url 'home:postanswer' detail.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" autocomplete="off" name="context" placeholder="Add description" required>
                <br>
                <input type="file" name="ans-file" placeholder="file here" required>
                <br>
                <input value="Add" type="submit">
            </form>
        
        </div>
    </div>
    <br>
    <hr>
   <div class="ans-area">

    {% if answers %}
    {% for ans in answers %}
<br>
      {{ans.context}}
    <br>
 <a href="{{ans.image.url}}" target="_blank">
    <img src="{{ans.image.url}}" width="500px" height="500px" style="color: blue;" alt="Click here for upbove answers,Pdf file">
    </a>
    <br>
    <div class="ans-owner">
        <p>from-{{ans.owner.username}} ||<small> {{ans.date_published}}</small> </p>
    </div>
    
{% if request.user.id == ans.owner.id %}
<div class="ans-function">
    <a href="{% url 'home:update_ans' detail.id ans.id %}">edit</a>
    <form   action="{% url 'home:delete_ans' detail.id ans.id %}" id="ans-delete-form">
        {% csrf_token %}
        <input value="delete" id="ans-delete-btn" type="submit">
        <script>
            const ans_btn = document.querySelector("#ans-delete-btn");
            ans_btn.addEventListener("click",() => {
           let will_delete = confirm("Are you sure?")
           if(will_delete == true){
             document.querySelector("#ans-delete-form").setAttribute("method","POST");
           }
           else{
               document.querySelector("#ans-delete-form").setAttribute("method","GET");
           }
       
       
            });
        </script>
    
    </form>
</div>
<hr>

{% else %}
<hr>
{% endif %}

{% endfor %}
{% else %}
    <p>No answers yet for these questions</p>

{% endif %}
   </div>


</section>





</main>
{% endblock %}

home/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
</head>
<body>
Forbidden
<br>
You can't access to this page
</body>
</html>

home/templates/index.html
{% extends 'base.html' %}
{% block meta %}
<meta name="description" content="This shows all the previous year Questions in one place">
<meta name="keywords" name="MIT previous year Questions">
{% endblock %}
 {% block title %}Home-all{% endblock %}
  {% load static%} 
  {% block style%}

<link rel="stylesheet" href="{% static 'css/index.css' %}" />

{% endblock %} 
{% block search %}


<div class="messages">
  <!-- <h3>Message here</h3> -->
  <div class="mssg">
    {% if messages %}
    <script>
      const msg = document.querySelector('.messages');
       msg.style.display = 'flex'
    </script>
     {% for messages in messages %}
         <p>{{messages}}</p>
     {% endfor %} 
  {% endif %}
  {% if error %}
  <script>
    const msg = document.querySelector('.messages');
     msg.style.display = 'flex'
  </script>
     <p>{{error}}</p>
  {% endif %}

  </div>
  <div class="close">
    <h5>&#10062</h5>
  </div>

</div>

<section id="search">
  <div class="search-container">
    <h2>Search here</h2>

    <form class="" action="{% url 'home:search' %}" method="get">
      <div class="row-search">
        <div class="col">
          <label for="">Trade</label>
          <select class="" name="trade_sec">
            <option selected="true" disabled="true">TRADE</option>
            {% for key,value in trades.items %}
            <option value="{{key}}">{{value}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <label for="">Semester</label>
          <select class="" name="sem_sec">
            <option selected="true" disabled="true">SEMESTER</option>
            {% for key,value in sems.items %}
            <option value="{{key}}">{{value}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <label for="">Exam</label>
          <select class="" name="exm">
            <option selected="true" disabled="true">EXAM</option>
            {% for key,value in exm.items %}
            <option value="{{key}}">{{value}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <label for="">Year</label>
          <select class="" name="year_sec">
            <option selected="true" disabled="true">Year</option>
            {% for item in yr %}
            <option value="{{item.value}}">{{item.year}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <label for="">Subject</label>
          <select class="" name="sub_sec">
            <option selected="true" disabled="true">Subject</option>
            {% for key,value in subject.items %}
            <option value="{{key}}">{{value}}</option>
            {% endfor %}
          </select>
        </div>

        <div class="search-btn-container">
          <input type="submit" name="" value="Search" class="btn" />
        </div>
      </div>
    </form>
  </div>
</section>

<hr />



{% endblock %} 


{% block content %} 

 <section id="files">

  <div class="files-container">
<!-- -----------card-container------------ -->
 {% if fiels %}
 {% for i in fiels %}
 <a class="detail-link" href="{% url 'home:detail' i.id %}">
     <div class="card-container">
     
       <div class="card-body">
           <ul>
             <h3>{{i.subject}}</h3>
             <li>semester: {{i.semester}}</li>
             <li>trade: {{i.trade}}</li>
             <li>year: {{i.year_of_exm}}</li>
             <li>exam: {{i.exam}}</li>
           </ul>
       </div>
       <div class="card-download">
              <a class="card-btn" href="{{i.file.url}}" target="_blank">Download file</a>
       </div>
       
     </div>
    </a>
     {% endfor %}
  {% else %}
  <div class="no-files">
    <h3>No files yet!!! You can upload or let your friends upload</h3>
  </div>

  {% endif %}
<!-- -----------card-container------------ -->


  </div>

 </section>


{% endblock %}